.\" $Id: nebula.man,v 1.14 2020/05/21 19:31:21 lhf Exp $
.TH NEBULA 1 "$Date: 2020/05/21 19:31:21 $"
.SH NAME
nebula \- Nebula interpreter
.SH SYNOPSIS
.B nebula
[
.I options
]
[
.I script
[
.I args
]
]
.SH DESCRIPTION
.B nebula
is the standalone Nebula interpreter.
It loads and executes Nebula programs,
either in textual source form or
in precompiled binary form.
(Precompiled binaries are output by
.BR nebulac ,
the Nebula compiler.)
.B nebula
can be used as a batch interpreter and also interactively.
.LP
After handling the
.IR options ,
the Nebula program in file
.I script
is loaded and executed.
The
.I args
are available to
.I script
as strings in a global table named
.B arg
and also as arguments to its main function.
When called without arguments,
.B nebula
behaves as
.B "nebula \-v \-i"
if the standard input is a terminal,
and as
.B "nebula \-"
otherwise.
.LP
In interactive mode,
.B nebula
prompts the user,
reads lines from the standard input,
and executes them as they are read.
If the line contains an expression,
then the line is evanebulated and the result is printed.
If a line does not contain a complete statement,
then a secondary prompt is displayed and
lines are read until a complete statement is formed or
a syntax error is found.
.LP
Before handling command line options and scripts,
.B nebula
checks the contents of the environment variables
.B NEBULA_INIT_5_4
and
.BR NEBULA_INIT ,
in that order.
If the contents are of the form
.RI '@ filename ',
then
.I filename
is executed.
Otherwise, the contents are assumed to be a Nebula statement and is executed.
When
.B NEBULA_INIT_5_4
is defined,
.B NEBULA_INIT
is ignored.
.SH OPTIONS
.TP
.BI \-e " stat"
execute statement
.IR stat .
.TP
.B \-i
enter interactive mode after executing
.IR script .
.TP
.BI \-l " name"
require library
.I name
into global
.IR name .
.TP
.B \-v
show version information.
.TP
.B \-E
ignore environment variables.
.TP
.B \-W
turn warnings on.
.TP
.B \-\-
stop handling options.
.TP
.B \-
stop handling options and execute the standard input as a file.
.SH ENVIRONMENT VARIABLES
The following environment variables affect the execution of
.BR nebula .
When defined,
the version-specific variants take priority
and the version-neutral variants are ignored.
.TP
.B NEBULA_INIT, NEBULA_INIT_5_4
Code to be executed before command line options and scripts.
.TP
.B NEBULA_PATH, NEBULA_PATH_5_4
Initial value of package.cpath,
the path used by require to search for Nebula loaders.
.TP
.B NEBULA_CPATH, NEBULA_CPATH_5_4
Initial value of package.cpath,
the path used by require to search for C loaders.
.SH EXIT STATUS
If a script calls os.exit,
then
.B nebula
exits with the given exit status.
Otherwise,
.B nebula
exits
with EXIT_SUCCESS (0 on POSIX systems) if there were no errors
and
with EXIT_FAILURE (1 on POSIX systems) if there were errors.
Errors raised in interactive mode do not cause exits.
.SH DIAGNOSTICS
Error messages should be self explanatory.
.SH "SEE ALSO"
.BR nebulac (1)
.br
The documentation at nebula.org,
especially section 7 of the reference manual.
.SH AUTHORS
R. Ierusalimschy,
L. H. de Figueiredo,
W. Celes
.\" EOF
