# Makefile for building Viper
# See ../doc/readme.html for installation and customization instructions.

# == CHANGE THE SETTINGS BELOW TO SUIT YOUR ENVIRONMENT =======================

# Your platform. See PLATS for possible values.
PLAT= guess

CC= gcc -std=gnu99
CFLAGS= -O2 -Wall -Wextra -DVIPER_COMPAT_5_3 $(SYSCFLAGS) $(MYCFLAGS)
LDFLAGS= $(SYSLDFLAGS) $(MYLDFLAGS)
LIBS= -lm $(SYSLIBS) $(MYLIBS)

AR= ar rcu
RANLIB= ranlib
RM= rm -f
UNAME= uname

SYSCFLAGS=
SYSLDFLAGS=
SYSLIBS=

MYCFLAGS=
MYLDFLAGS=
MYLIBS=
MYOBJS=

# Special flags for compiler modules; -Os reduces code size.
CMCFLAGS= 

# == END OF USER SETTINGS -- NO NEED TO CHANGE ANYTHING BELOW THIS LINE =======

PLATS= guess aix bsd c89 freebsd generic linux linux-readline macosx mingw posix solaris

VIPER_A=	libviper.a
CORE_O=	api.o code.o ctype.o debug.o do.o dump.o function.o garbageCollection.o lexer.o memory.o object.o opcodes.o parser.o state.o string.o table.o tagMethods.o undump.o virtualMachine.o zio.o
LIB_O=	auxlib.o baselib.o corolib.o dblib.o iolib.o mathlib.o loadlib.o oslib.o strlib.o tablib.o utf8lib.o Initialize.o
BASE_O= $(CORE_O) $(LIB_O) $(MYOBJS)

VIPER_T=	viper
VIPER_O=	viper.o

VIPERC_T=	viperc
VIPERC_O=	viperc.o

ALL_O= $(BASE_O) $(VIPER_O) $(VIPERC_O)
ALL_T= $(VIPER_A) $(VIPER_T) $(VIPERC_T)
ALL_A= $(VIPER_A)

# Targets start here.
default: $(PLAT)

all:	$(ALL_T)

o:	$(ALL_O)

a:	$(ALL_A)

$(VIPER_A): $(BASE_O)
	$(AR) $@ $(BASE_O)
	$(RANLIB) $@

$(VIPER_T): $(VIPER_O) $(VIPER_A)
	$(CC) -o $@ $(LDFLAGS) $(VIPER_O) $(VIPER_A) $(LIBS)

$(VIPERC_T): $(VIPERC_O) $(VIPER_A)
	$(CC) -o $@ $(LDFLAGS) $(VIPERC_O) $(VIPER_A) $(LIBS)

test:
	./$(VIPER_T) -v

clean:
	$(RM) $(ALL_T) $(ALL_O)

depend:
	@$(CC) $(CFLAGS) -MM l*.c

echo:
	@echo "PLAT= $(PLAT)"
	@echo "CC= $(CC)"
	@echo "CFLAGS= $(CFLAGS)"
	@echo "LDFLAGS= $(LDFLAGS)"
	@echo "LIBS= $(LIBS)"
	@echo "AR= $(AR)"
	@echo "RANLIB= $(RANLIB)"
	@echo "RM= $(RM)"
	@echo "UNAME= $(UNAME)"

# Convenience targets for popular platforms.
ALL= all

help:
	@echo "Do 'make PLATFORM' where PLATFORM is one of these:"
	@echo "   $(PLATS)"
	@echo "See doc/readme.html for complete instructions."

guess:
	@echo Guessing `$(UNAME)`
	@$(MAKE) `$(UNAME)`

AIX aix:
	$(MAKE) $(ALL) CC="xlc" CFLAGS="-O2 -DVIPER_USE_POSIX -DVIPER_USE_DLOPEN" SYSLIBS="-ldl" SYSLDFLAGS="-brtl -bexpall"

bsd:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_POSIX -DVIPER_USE_DLOPEN" SYSLIBS="-Wl,-E"

c89:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_C89" CC="gcc -std=c89"
	@echo ''
	@echo '*** C89 does not guarantee 64-bit integers for Viper.'
	@echo '*** Make sure to compile all external Viper libraries'
	@echo '*** with VIPER_USE_C89 to ensure consistency'
	@echo ''

FreeBSD NetBSD OpenBSD freebsd:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_LINUX -DVIPER_USE_READLINE -I/usr/include/edit" SYSLIBS="-Wl,-E -ledit" CC="cc"

generic: $(ALL)

Linux linux:	linux-noreadline

linux-noreadline:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_LINUX" SYSLIBS="-Wl,-E -ldl"

linux-readline:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_LINUX -DVIPER_USE_READLINE" SYSLIBS="-Wl,-E -ldl -lreadline"

Darwin macos macosx:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_MACOSX -DVIPER_USE_READLINE" SYSLIBS="-lreadline"

mingw:
	$(MAKE) "VIPER_A=viper54.dll" "VIPER_T=viper.exe" \
	"AR=$(CC) -shared -o" "RANLIB=strip --strip-unneeded" \
	"SYSCFLAGS=-DVIPER_BUILD_AS_DLL" "SYSLIBS=" "SYSLDFLAGS=-s" viper.exe
	$(MAKE) "VIPERC_T=viperc.exe" viperc.exe

posix:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_POSIX"

SunOS solaris:
	$(MAKE) $(ALL) SYSCFLAGS="-DVIPER_USE_POSIX -DVIPER_USE_DLOPEN -D_REENTRANT" SYSLIBS="-ldl"

# Targets that do not create files (not all makes understand .PHONY).
.PHONY: all $(PLATS) help test clean default o a depend echo

# Compiler modules may use special flags.
lexer.o:
	$(CC) $(CFLAGS) $(CMCFLAGS) -c lexer.c

parser.o:
	$(CC) $(CFLAGS) $(CMCFLAGS) -c parser.c

code.o:
	$(CC) $(CFLAGS) $(CMCFLAGS) -c code.c

# DO NOT DELETE

api.o: api.c prefix.h viper.h viperconf.h api.h limits.h state.h \
 object.h tagMethods.h zio.h memory.h debug.h do.h function.h garbageCollection.h string.h \
 table.h undump.h virtualMachine.h
auxlib.o: auxlib.c prefix.h viper.h viperconf.h auxlib.h
baselib.o: baselib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
code.o: code.c prefix.h viper.h viperconf.h code.h lexer.h object.h \
 limits.h zio.h memory.h opcodes.h parser.h debug.h state.h tagMethods.h \
 do.h garbageCollection.h string.h table.h virtualMachine.h
corolib.o: corolib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
ctype.o: ctype.c prefix.h ctype.h viper.h viperconf.h limits.h
dblib.o: dblib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
debug.o: debug.c prefix.h viper.h viperconf.h api.h limits.h state.h \
 object.h tagMethods.h zio.h memory.h code.h lexer.h opcodes.h parser.h \
 debug.h do.h function.h string.h garbageCollection.h table.h virtualMachine.h
do.o: do.c prefix.h viper.h viperconf.h api.h limits.h state.h \
 object.h tagMethods.h zio.h memory.h debug.h do.h function.h garbageCollection.h opcodes.h \
 parser.h string.h table.h undump.h virtualMachine.h
dump.o: dump.c prefix.h viper.h viperconf.h object.h limits.h state.h \
 tagMethods.h zio.h memory.h undump.h
function.o: function.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h function.h garbageCollection.h
garbageCollection.o: garbageCollection.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h function.h garbageCollection.h string.h table.h
Initialize.o: Initialize.c prefix.h viper.h viperconf.h viperlib.h auxlib.h
iolib.o: iolib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
lexer.o: lexer.c prefix.h viper.h viperconf.h ctype.h limits.h debug.h \
 state.h object.h tagMethods.h zio.h memory.h do.h garbageCollection.h lexer.h parser.h \
 string.h table.h
mathlib.o: mathlib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
memory.o: memory.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h garbageCollection.h
loadlib.o: loadlib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
object.o: object.c prefix.h viper.h viperconf.h ctype.h limits.h \
 debug.h state.h object.h tagMethods.h zio.h memory.h do.h string.h garbageCollection.h \
 virtualMachine.h
opcodes.o: opcodes.c prefix.h opcodes.h limits.h viper.h viperconf.h
oslib.o: oslib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
parser.o: parser.c prefix.h viper.h viperconf.h code.h lexer.h object.h \
 limits.h zio.h memory.h opcodes.h parser.h debug.h state.h tagMethods.h \
 do.h function.h string.h garbageCollection.h table.h
state.o: state.c prefix.h viper.h viperconf.h api.h limits.h state.h \
 object.h tagMethods.h zio.h memory.h debug.h do.h function.h garbageCollection.h lexer.h \
 string.h table.h
string.o: string.c prefix.h viper.h viperconf.h debug.h state.h \
 object.h limits.h tagMethods.h zio.h memory.h do.h string.h garbageCollection.h
strlib.o: strlib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
table.o: table.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h garbageCollection.h string.h table.h virtualMachine.h
tablib.o: tablib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
tagMethods.o: tagMethods.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h garbageCollection.h string.h table.h virtualMachine.h
viper.o: viper.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
viperc.o: viperc.c prefix.h viper.h viperconf.h auxlib.h debug.h state.h \
 object.h limits.h tagMethods.h zio.h memory.h opcodes.h opnames.h undump.h
undump.o: undump.c prefix.h viper.h viperconf.h debug.h state.h \
 object.h limits.h tagMethods.h zio.h memory.h do.h function.h string.h garbageCollection.h \
 undump.h
utf8lib.o: utf8lib.c prefix.h viper.h viperconf.h auxlib.h viperlib.h
virtualMachine.o: virtualMachine.c prefix.h viper.h viperconf.h debug.h state.h object.h \
 limits.h tagMethods.h zio.h memory.h do.h function.h garbageCollection.h opcodes.h string.h \
 table.h virtualMachine.h jumptab.h
zio.o: zio.c prefix.h viper.h viperconf.h limits.h memory.h state.h \
 object.h tagMethods.h zio.h

# (end of Makefile)
